name: LLMOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-scan-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3️⃣ Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # 4️⃣ Build and push Docker image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/gpt-hf-service:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/gpt-hf-service:${{ github.sha }}

    # 5️⃣ Scan image with Trivy
    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@v0.33.0
      with:
        image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/gpt-hf-service:latest
        format: table
        exit-on-vuln: false

    # 6️⃣ Set up kubectl
    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    # 7️⃣ Deploy to Kubernetes
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yml
        kubectl apply -f service.yml
        kubectl rollout status deployment/gpt-hf
