name: LLMOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-scan-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3️⃣ Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # 4️⃣ Build and push Docker image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          chingyee001120/fastapi-app:latest
          chingyee001120/fastapi-app:${{ github.sha }}

    # 5️⃣ Scan image with Trivy
    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@0.12.0
      with:
        image-ref: chingyee001120/fastapi-app:latest
        format: table
        exit-on-vuln: false
        timeout: 15m          # increase timeout to 10 minutes
        scan-type: image
        ignore-unfixed: false
        # skip-update: true    # uncomment if DB updates are slow or fail

    # 6️⃣ Set up kubeconfig 
    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    # 7️⃣ Deploy to Kubernetes
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yml
        kubectl apply -f service.yml
        kubectl rollout status deployment/gpt-huggingface
        