name: LLMOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-scan-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/chingyee001120/fastapi-app:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/chingyee001120/fastapi-app:${{ github.sha }}

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@0.12.0
      with:
        image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/chingyee001120/fastapi-app:latest
        format: table
        exit-on-vuln: false

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yml
        kubectl apply -f service.yml
        kubectl rollout status deployment/gpt-hf
